export const TOGGLE_FILTERS = 'TOGGLE_FILTERS';

export const SET_LOADING = 'SET_LOADING';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';

export const REQUEST_FILTERS = 'REQUEST_FILTERS';
export const RECEIVE_FILTERS = 'RECEIVE_FILTERS';
export const ERROR_FILTERS = 'ERROR_FILTERS';

export const REQUEST_PLANTS = 'REQUEST_PLANTS';
export const RECEIVE_PLANTS = 'RECEIVE_PLANTS';
export const ERROR_PLANTS = 'ERROR_PLANTS';

export const SET_SEARCH = 'SET_SEARCH';

export const OPEN_NEW_PLANT = 'OPEN_NEW_PLANT';
export const OPEN_EXISTING_PLANT = 'OPEN_EXISTING_PLANT';
export const CLOSE_PLANT = 'CLOSE_PLANT';
export const SAVE_PLANT = 'SAVE_PLANT';
export const SAVE_PLANT_SUCCESS = 'SAVE_PLANT_SUCCESS';
export const SAVE_PLANT_ERROR = 'SAVE_PLANT_ERROR';
export const DELETE_PLANT = 'DELETE_PLANT';
export const DELETE_PLANT_SUCCESS = 'DELETE_PLANT_SUCCESS';
export const DELETE_PLANT_ERROR = 'DELETE_PLANT_ERROR';


export const REQUEST_PLANT_INFO = 'REQUEST_PLANT_INFO';
export const RECEIVE_PLANT_INFO = 'RECEIVE_PLANT_INFO';
export const ERROR_PLANT_INFO = 'ERROR_PLANT_INFO';
export const DONE_PLANT_INFO = 'DONE_PLANT_INFO';
