export const TOGGLE_FILTERS = 'TOGGLE_FILTERS';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const REQUEST_FILTERS = 'REQUEST_FILTERS';
export const RECEIVE_FILTERS = 'RECEIVE_FILTERS';
export const ERROR_FILTERS = 'ERROR_FILTERS';

export const REQUEST_PLANTS = 'REQUEST_PLANTS';
export const RECEIVE_PLANTS = 'RECEIVE_PLANTS';
export const ERROR_PLANTS = 'ERROR_PLANTS';

export const SET_SEARCH = 'SET_SEARCH';